trigger:
  - master

pool:
  name: "Default" # Replace with your agent pool name

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - script: |
      npm install -g @angular/cli
    displayName: "Install Angular CLI"

  - script: |
      npm install
    displayName: "Installing Dependencies"

  - script: |
      ng build
    displayName: "Build Angular App"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/dist/slider"
      includeRootFolder: true
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/slider.zip"
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)/slider.zip"
      artifactName: "drop"
    displayName: "Publish Artifact"
